-- ***********************
-- Name: Adam Jemal
-- ID: 131017188
-- ***********************

-- Q1 Solution --
SELECT
  OFFICECODE, CITY, STATE, COUNTRY, PHONE
FROM
  OFFICES;

-- Q2 Solution --
SELECT
  EMPLOYEENUMBER, FIRSTNAME, LASTNAME, EXTENSION
FROM
  EMPLOYEES
WHERE 
  OFFICECODE = 1;

-- Q3 Solution --
SELECT
  CUSTOMERNUMBER, CUSTOMERNAME, CONTACTFIRSTNAME, CONTACTLASTNAME, PHONE
FROM
  CUSTOMERS
WHERE 
  CITY = 'Paris';

-- Q4 Solution --
SELECT
  CUSTOMERNUMBER, CUSTOMERNAME,
  CONCAT
    ( 
    CONTACTLASTNAME,
    CONTACTFIRSTNAME
    )
  AS 
    "Contact Name",
  PHONE
FROM
  CUSTOMERS
WHERE 
  COUNTRY = 'Canada';

-- Q5 Solution --
SELECT
  DISTINCT
  CUSTOMERNUMBER
FROM
  PAYMENTS
WHERE 
  AMOUNT > 0
ORDER BY 
  CUSTOMERNUMBER
FETCH FIRST 
  10 ROWS ONLY;

-- Q6 Solution --
SELECT
  CUSTOMERNUMBER, CHECKNUMBER, AMOUNT
FROM
  PAYMENTS
WHERE 
  AMOUNT NOT BETWEEN 1500 AND 120000
ORDER BY
    AMOUNT DESC;

-- Q7 Solution --
SELECT
  ORDERNUMBER, ORDERDATE, STATUS, CUSTOMERNUMBER
FROM
  ORDERS
WHERE 
  STATUS = 'Cancelled'
ORDER BY 
  ORDERDATE;

-- Q8 Solution --
SELECT
  PRODUCTCODE, PRODUCTNAME, BUYPRICE, MSRP,
  MSRP - BUYPRICE AS markup,
  round(100 * (MSRP - BUYPRICE) / BUYPRICE, 1) AS percmarkup
FROM
  PRODUCTS
WHERE 
  round (100 * (MSRP - BUYPRICE) / BUYPRICE, 1) > 140
ORDER BY 
  round (100 * (MSRP - BUYPRICE) / BUYPRICE, 1);

-- Q9 Solution --

SELECT
  PRODUCTCODE, PRODUCTNAME, QUANTITYINSTOCK
FROM
  PRODUCTS
WHERE 
  PRODUCTNAME LIKE '%co%'
ORDER BY 
  QUANTITYINSTOCK;

-- Q10 Solution --
SELECT
  CUSTOMERNUMBER,
  CONTACTFIRSTNAME,
  CONTACTLASTNAME
FROM
  CUSTOMERS
WHERE 
    LOWER(CONTACTFIRSTNAME) LIKE 's%e%'
ORDER BY 
    CUSTOMERNUMBER;